### ISSUE TITLE
Class 'Bnb\PushNotifications\PushServiceProvider' not found 

### ISSUE THREAD

**Issue by michelmelo** [bnbwebexpertise/laravel-push-notifications#1]
hello I'm in trouble when installing your package. error:

Class 'Bnb\PushNotifications\PushServiceProvider' not found

**Comment by gabsource** [comment]
Hi,

We made a typo error in the readme. The service provider class name is `Bnb\PushNotifications\PushNotificationsServiceProvider::class`.

Thanks for reporting this.
